server.port=8000
primary.host=http://localhost:9000
secondary.host=http://localhost:9001
candidate.host=http://localhost:9002

debug=true

# Delay in milliseconds before unsetting global traceId context
degressly.core.traceid.cleanup.delay=5000

# Downstream service host
degressly.downstream.host=localhost:8080

# Feature flag to enable/disable global traceId context API calls
degressly.core.traceid.context.enabled=false
